### PR TITLE
pwm: pwm-ts: Fix inversed before enabling pwm

### LINKED ISSUE #74: pwm-ts: Allow setting polarity on boot without enabling
https://github.com/embeddedTS/linux-lts/blob/linux-5.10.y/drivers/pwm/pwm-ts.c#L140

We might need to implement the hooks:
disable
set_polarity

Or "apply" might be called when we are disabled, which appears to be the case since we handle disabling the state in apply. We should determine if we can implement a default idle state before a cycle is issued.

As a workaround for now, it looks like enabling a period/duty cycle with a polarity, and then disabling it would set an idle state.

### PR DESCRIPTION
**Pull request by markfeathers**
This allows inversed to be set without first turning on the PWM. This also removes the state in the ts object that was tracking state, and now the calc function sets the registers. Removed the spinlock which is not used or needed.

### CODE REVIEW

**Review by randytsi369 — DISMISSED** [review]
Reviewed, not tested.

**Review by luckshot — DISMISSED** [review]

**Comment by ts-kris** [comment]
I havn't forgot about this, just had higher priority things on my plate. If this is super urgent I can cut over and test

File: drivers/pwm/pwm-ts.c [hunk 1]
```diff
@@ -90,49 +83,36 @@ static int ts_pwm_calc(struct ts_pwm *ts,
...
-
-		ts->shift = shift;
-		ts->period = cnt;
-		ts->duty = cnt - duty_cnt;
+		duty_reg = cnt - duty_cnt;
 	}
 
+	writew(cnt, ts->base + REG_PERIOD);
+	writew(duty_reg, ts->base + REG_DUTY);
+	writew(shift, ts->base + REG_SHIFT);
```
Comment (ts-kris) [inline drivers/pwm/pwm-ts.c:91]: I'm curious what this looks like on the PWM line when there is a change? In looking at other PWM drivers, it looks like in general they rely on hardware to only apply settings at a specific time. I'm not sure what our core does in this case. If it is really glitchy, we might consider disabling the PWM, applying settings, and then enabling the PWM?

File: drivers/pwm/pwm-ts.c [hunk 2]
```diff
@@ -90,49 +83,36 @@ static int ts_pwm_calc(struct ts_pwm *ts,
...
-		return 0;
-	}
+	u16 ctrl = 0;
 
 	if (state->polarity == PWM_POLARITY_NORMAL)
-		value &= ~(INVERSED);
+		ctrl &= ~INVERSED;
 	else
-		value |= INVERSED;
+		ctrl |= INVERSED;
```
Comment (ts-kris) [inline drivers/pwm/pwm-ts.c]: This can be just
```
if (state->polarity != PWM_POLARITY_NORMAL)
		ctrl |= INVERSED;
```

No need for the if/else

Comment (markfeathers) [reply drivers/pwm/pwm-ts.c]: Good point, will fix.

File: drivers/pwm/pwm-ts.c (hunk 1 above)
Comment (markfeathers) [reply drivers/pwm/pwm-ts.c:91]: The PWM framework enforces that the period does not change when the PWM channel is enabled. I based this on pwm-mxs which does seem to write its own registers similarly. The period changing is all that can influence our period/shift registers having different values, so the only piece that can change is duty. The FPGA core is safe to change duty at any time. I could update this in code to check if its enabled, but I'd have to store the cnt/cycle values from when period actually is set. Its certainly doable to store & have different paths for if its enabled or not to save the extra calculation / write when the user is only changing duty, but I'm tempted to leave that until we have a need to change duty faster.

Comment (ts-kris) [reply drivers/pwm/pwm-ts.c:91]: No, no, that should be okay.
> The PWM framework enforces that the period does not change when the PWM channel is enabled.

I was unaware of that, and as shift is only affected by period, then only duty would ever change and all of this should be safe.

**Review by ts-kris — APPROVED** [review]

**Review by randytsi369 — APPROVED** [review]
Reviewed, not tested.
